### ISSUE TITLE
language doesn't switch

### ISSUE THREAD

**Issue by nottakis** [baby-degu/docusaurus#4]

**Comment by ryuckel** [comment]
I found below error message. I will check more detail.
`Could not find a string translation in 'ja' for string 'Help Translate|recruit community translators for your project'. Using English version instead.`

**Comment by nottakis** [comment]
Thanks ryuckel!

As far as I understand, the text on the .md and .js files will be translated differently. 
I guess the error message you mentioned should be from the latter ones. 

I don't still know how to set up the language switch for the .md. 
Maybe because of the path location, or we need additional settings.

**Comment by nottakis** [comment]
This maybe? I'm not sure. 

crowdin.yaml
```
files:
  - source: '/docs/**/*.md'
    translation: '/website/translated_docs/%locale%/**/%original_file_name%'
    languages_mapping: &anchor
```

* What I've already checked
https://docusaurus.io/docs/en/translation#markdown-files
